export interface ProcessEnv {
  OPENAI_API_KEY: string;
  OPENAI_API_HOST?: string;
  OPENAI_API_TYPE?: 'openai' | 'azure';
  OPENAI_API_VERSION?: string;
  OPENAI_ORGANIZATION?: string;
  // 追加した環境変数
  NEXT_PUBLIC_PAGE_TITLE?: string;
  NEXT_PUBLIC_CHATBOT_NAME?: string;
  NEXT_PUBLIC_MESSAGE_TITLE?: string;
  NEXT_PUBLIC_CUSTOMIZED_MESSAGE1?: string;
  NEXT_PUBLIC_CUSTOMIZED_MESSAGE2?: string;
  NEXT_PUBLIC_CUSTOMIZED_MESSAGE3?: string;
  NEXT_PUBLIC_CUSTOMIZED_MESSAGE4?: string;
  NEXT_PUBLIC_CUSTOMIZED_MESSAGE5?: string;
  NEXT_PUBLIC_APPLICATION_DESCRIPTION?: string;
}
